# Session 50: Multiple Linear Regression

[Watch Here](https://www.youtube.com/live/e_9vJXokd-Y?si=O63OTtr8osaYpWFB)

## Multiple Linear Regression

In [1]:
# Import necessary libraries for data generation, manipulation, visualization, and evaluation
import numpy as np
import pandas as pd
from sklearn.datasets import make_regression


import plotly.express as px
import plotly.graph_objects as go

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [2]:
# Generate a synthetic 3D regression dataset with 100 samples and 2 features
X, y = make_regression(n_samples=100, n_features=2, n_informative=2, n_targets=1, noise=50)

In [3]:
# Create a pandas DataFrame containing features and the target variable
df = pd.DataFrame({'feature1':X[:,0],'feature2':X[:,1],'target':y})

In [4]:
### Check the dimensions (rows, columns) of the generated DataFrame
df.shape

(100, 3)

In [5]:
# Create and display a 3D scatter plot of our dataset using Plotly Express
fig = px.scatter_3d(df, x='feature1', y='feature2', z='target')
fig.show()

In [6]:
# Split the generated data into training (80%) and testing (20%) sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=3)

In [7]:
# Import the LinearRegression model class from scikit-learn
from sklearn.linear_model import LinearRegression

In [8]:
# Instantiate the linear regression model object
lr = LinearRegression()

In [9]:
# Fit (train) the Linear Regression model on the training data
lr.fit(X_train, y_train)

LinearRegression()

In [10]:
# Use the trained model to predict the target values for the test set
y_pred = lr.predict(X_test)

In [11]:
# Calculate and print the performance metrics (MAE, MSE, and R2 Score) on the test predictions
print('MAE ->', mean_absolute_error(y_test, y_pred))
print('MSE ->', mean_squared_error(y_test, y_pred))
print('R2 Score ->', r2_score(y_test, y_pred))

MAE -> 50.416889888739966
MSE -> 4071.126461066706
R2 Score -> 0.7053722653039665


In [12]:
# Set up coordinate grids and predict predictions across the feature space to draw the regression plane
x = np.linspace(-5, 5, 10)
y = np.linspace(-5, 5, 10)

xGrid, yGrid = np.meshgrid(y, x)

final = np.vstack((xGrid.ravel().reshape(1,100), yGrid.ravel().reshape(1,100))).T

z_final = lr.predict(final).reshape(10,10)

z = z_final

In [13]:
# Plot the original data points and superimpose the 3D regression decision boundary plane
fig = px.scatter_3d(df, x='feature1', y='feature2', z='target')

fig.add_trace(go.Surface(x = x, y = y, z = z))

fig.show()

In [14]:
# Retrieve the calculated slope coefficients for each feature
lr.coef_

array([89.61516626, 22.09105512])

In [15]:
# Retrieve the calculated y-intercept value of the regression line
lr.intercept_

np.float64(-0.693108949928229)

## Code From Scratch

In [16]:
# Import numpy and the load_diabetes helper function from sklearn datasets
import numpy as np
from sklearn.datasets import load_diabetes

In [17]:
# Load the diabetes dataset returning features (X) and target targets (y)
X, y = load_diabetes(return_X_y=True)

In [18]:
# Display the raw feature matrix
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [19]:
# Inspect the dimensions of the feature matrix
X.shape

(442, 10)

In [20]:
# Display the raw target array values
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [21]:
# Inspect the dimensions of the target array
y.shape

(442,)

### Using Sklearn's Linear Regression

In [22]:
# Import train_test_split utility from scikit-learn
from sklearn.model_selection import train_test_split

In [23]:
# Split the diabetes dataset into 80% training and 20% testing subsets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2)

In [24]:
# Print the dimensions of the training and test sets to confirm split shape
print(X_train.shape)
print(X_test.shape)

(353, 10)
(89, 10)


In [25]:
# Import the LinearRegression model class from scikit-learn
from sklearn.linear_model import LinearRegression

In [26]:
# Instantiate the linear regression model object
reg = LinearRegression()

In [27]:
# Fit the linear regression model onto the diabetes training split data
reg.fit(X_train, y_train)

LinearRegression()

In [28]:
# Generate predictions for the diabetes test split target variable
y_pred = reg.predict(X_test)

In [29]:
# Import the R-squared evaluation metric from scikit-learn metrics module
from sklearn.metrics import r2_score

In [30]:
# Compute and display the R2 score comparing predictions with ground truth targets
r2_score(y_test, y_pred)

0.4399338661568968

In [31]:
# Retrieve the computed feature coefficients for the diabetes regression model
reg.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [32]:
# Retrieve the computed y-intercept of the diabetes regression model
reg.intercept_

np.float64(151.88331005254167)

### Making our own Linear Regression Class

In [33]:
# Define a custom Multiple Linear Regression class using the Closed-Form OLS Formulation
class MeraLR:

    def __init__(self):
        self.coef_ = None
        self.intercept_ = None

    def fit(self, X_train, y_train):
        # Insert a column of 1s at index 0 for the intercept/bias term
        X_train = np.insert(X_train, 0, 1, axis=1)

        # Solve for coefficients using normal equation: (X^T * X)^(-1) * X^T * y
        betas = np.linalg.inv(np.dot(X_train.T, X_train)).dot(X_train.T).dot(y_train)
        self.intercept_ = betas[0]
        self.coef_ = betas[1:]

    def predict(self, X_test):
        # Compute the dot product of test data and coefficients, then add the intercept
        y_pred = np.dot(X_test, self.coef_) + self.intercept_
        return y_pred

In [34]:
# Instantiate our custom MeraLR class object
lr = MeraLR()

In [35]:
# Train our custom closed-form Multiple Linear Regression model on training data
lr.fit(X_train, y_train)

In [36]:
# Inspect the dimensions of the original training feature matrix
X_train.shape

(353, 10)

In [37]:
# Preview the shape after prepend/insertion of bias column filled with ones
np.insert(X_train, 0, 1, axis=1).shape

(353, 11)

In [38]:
# Generate targets predictions using our custom model on test subset data
y_pred = lr.predict(X_test)

In [39]:
# Evaluate performance by computing R2 score for custom implementation predictions
r2_score(y_test,y_pred)

0.43993386615689634

In [40]:
# Retrieve coefficients calculated by our custom closed-form normal equation formulation
lr.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [41]:
# Retrieve intercept term calculated by our custom closed-form normal equation formulation
lr.intercept_

np.float64(151.88331005254165)